name: dotnet_application

on: push

jobs:
  delivery:
    runs-on: windows-latest
    name: build, test, deliver container
    steps:
      - name: Check out repository
        uses: actions/checkout@v1

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.402

      - name: Docker login
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker Build
        run: docker build -t ${{ secrets.DOCKER_USER }}twitter-app:latest .
Z
      - name: Upload container to Docker Hub with Push
        run: docker push ${{ secrets.DOCKER_USER }}/twitter-app:latest
